openapi: 3.0.0
info:
  title: API de Mascotas
  version: 1.0.0
  description: API para gestionar mascotas

paths:
  /api/pets:
    get:
      summary: Obtiene todas las mascotas
      tags:
        - Pets
      responses:
        '200':
          description: Lista de todas las mascotas
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specie:
                          type: string
                        birthDate:
                          type: string

    post:
      summary: Crea una nueva mascota
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                specie:
                  type: string
                birthDate:
                  type: string
                  format: date
      responses:
        '200':
          description: Mascota creada
        '400':
          description: Valores incompletos
